web:
  image: nginx
  ports:
    - "8080:80"
  volumes_from:
    - phpfiles
    - nginxconf
  links:
    - phpserver:phpserver


phpserver:
  image: jolicode/hhvm
  volumes_from:
    - phpfiles
  command: hhvm --mode server --config /etc/hhvm/php.ini --config /etc/hhvm/server.ini
  links:
    - db:mysql
    - memcache:memcache
  user: www-data


db:
  image: mariadb
  volumes_from:
    - varlibmysql
  environment:
    MYSQL_ROOT_PASSWORD: secret


memcache:
  image: memcached


phpfiles:
  image: tianon/true
  volumes:
    - ./php/:/usr/share/nginx/html:ro
  command: /true


nginxconf:
  image: tianon/true
  volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  command: /true


varlibmysql:
  image: tianon/true
  volumes:
    - ./db/:/var/lib/mysql
  command: /true
